<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c5ed1721-82b5-4c54-9b9d-0bff64db85fb</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="7.15.0" />
    <PackageReference Include="Npgsql.DependencyInjection" Version="9.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\App.Core\App.Core.csproj" />
    <ProjectReference Include="..\App.Data\App.Data.csproj" />
  </ItemGroup>
</Project>
